[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; lib_deps gerencia as bibliotecas
lib_deps =
    ; Biblioteca U8g2 para o display OLED
    olikraus/U8g2
    ; Biblioteca Display LCD
    #bodmer/TFT_eSPI //desativada por enquanto

    ; Biblioteca F1-25 UDP solicitada
    ;
    https://github.com/MacManley/f1-25-udp.git